version: "3.9"

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"

  order-service:
    build: ./order-service
    ports:
      - "8000:8000"

  product-service:
    build: ./product-service/product-service
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - user-service
      - order-service
      - product-service
